# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5e5c2a8666572e0ec48d5fe89f95c544246fb648ae73ab9c2e3dd496f4bd87ed7d4bab35139b501c1525658f237d0a9d8a03e544b29b4c61a253d421f541216

test:
  secret_key_base: 3aa9a003e2e94577e9675a628b75721865bc652d17209d1a8dac08d66013e3a197d12e51e7eae37750705afb2c4205ba100b9b91f18c5ff114e40bcb65401b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
